export const categories = [
  { id: 'sex', name: 'Секс знакомства', icon: 'Heart', color: 'bg-pink-100 text-pink-700' },
  { id: 'escort', name: 'Эскорт', icon: 'User', color: 'bg-purple-100 text-purple-700' },
  { id: 'couples', name: 'Пары МЖ', icon: 'Users2', color: 'bg-rose-100 text-rose-700' },
  { id: 'massage', name: 'Массаж', icon: 'Sparkles', color: 'bg-teal-100 text-teal-700' },
  { id: 'rent', name: 'Аренда', icon: 'Home', color: 'bg-blue-100 text-blue-700' },
  { id: 'tourism', name: 'Туризм', icon: 'MapPin', color: 'bg-green-100 text-green-700' },
  { id: 'fetish', name: 'Фетиш', icon: 'Star', color: 'bg-orange-100 text-orange-700' },
  { id: 'trans', name: 'Трансы', icon: 'Users', color: 'bg-indigo-100 text-indigo-700' },
  { id: 'bdsm', name: 'БДСМ', icon: 'Lock', color: 'bg-red-100 text-red-700' },
];

export const popularSearches = [
  'знакомства',
  'встреча',
  'девушка',
  'москва',
  'центр',
  'vip',
  'проверенная',
  'массаж',
];

export const mockComments: any = {
  1: [
    { id: 1, author: 'Александр', comment: 'Отличная встреча, всё на высшем уровне!', date: '2 дня назад', userId: 2 },
    { id: 2, author: 'Дмитрий', comment: 'Очень приятная девушка, рекомендую', date: '5 дней назад', userId: 3 },
    { id: 3, author: 'Михаил', comment: 'Хорошо, соответствует описанию', date: '1 неделю назад', userId: 4 },
  ],
  2: [
    { id: 1, author: 'Иван', comment: 'Премиальный сервис, всё идеально', date: '1 день назад', userId: 5 },
    { id: 2, author: 'Сергей', comment: 'Профессиональный подход, буду обращаться снова', date: '3 дня назад', userId: 6 },
  ],
};

export const profileEmojis = ['👤', '👨', '👩', '🧑', '👱‍♀️', '👱‍♂️', '🧔', '👨‍🦰', '👩‍🦰', '👨‍🦱', '👩‍🦱', '👨‍🦳', '👩‍🦳', '🧑‍🦰', '🧑‍🦱'];

export const getRandomEmoji = (id: number) => {
  return profileEmojis[id % profileEmojis.length];
};

export const mockListings = [
  {
    id: 1,
    title: 'Анна, 25 лет',
    category: 'sex',
    location: 'Москва, Центр',
    likes: 42,
    dislikes: 3,
    commentsCount: 24,
    verified: true,
    description: 'Приятная встреча, комфортная обстановка',
    price: '5000 ₽/час',
    isVip: false,
    boostedAt: null,
    ownerId: 1,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
    profile: {
      age: 25,
      weight: 55,
      height: 168,
      bodyType: 'Стройная',
      breastSize: '3',
      orientation: 'Гетеро',
      services: 'Классика, минет, массаж',
      intimateHaircut: 'Бразильская эпиляция',
      tattoos: 'Нет',
      piercings: 'Нет',
      smoking: 'Не курю',
      alcohol: 'Иногда',
    },
  },
  {
    id: 2,
    title: 'Элитное сопровождение VIP',
    category: 'escort',
    location: 'Москва, Пресня',
    likes: 89,
    dislikes: 2,
    commentsCount: 45,
    verified: true,
    description: 'Премиальный сервис для деловых встреч',
    price: '15000 ₽/час',
    isVip: true,
    boostedAt: Date.now(),
    ownerId: 1,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
  },
  {
    id: 3,
    title: 'Квартира посуточно',
    category: 'rent',
    location: 'Санкт-Петербург',
    likes: 28,
    dislikes: 5,
    commentsCount: 18,
    verified: false,
    description: 'Уютная квартира в центре города',
    price: '3000 ₽/сутки',
    isVip: false,
    boostedAt: null,
    ownerId: 2,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
  },
  {
    id: 4,
    title: 'Тур выходного дня',
    category: 'tourism',
    location: 'Сочи',
    likes: 56,
    dislikes: 8,
    commentsCount: 32,
    verified: true,
    description: 'Отдых на море с развлечениями',
    price: '25000 ₽',
    isVip: false,
    boostedAt: null,
    ownerId: 2,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
  },
  {
    id: 5,
    title: 'Мария, 28 лет',
    category: 'fetish',
    location: 'Москва, Юго-Запад',
    likes: 102,
    dislikes: 4,
    commentsCount: 56,
    verified: true,
    description: 'Особые встречи для ценителей',
    price: '8000 ₽/час',
    isVip: false,
    boostedAt: null,
    ownerId: 2,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
  },
  {
    id: 6,
    title: 'София, 24 года',
    category: 'trans',
    location: 'Москва, Арбат',
    likes: 64,
    dislikes: 6,
    commentsCount: 29,
    verified: true,
    description: 'Яркая и запоминающаяся встреча',
    price: '6000 ₽/час',
    isVip: false,
    boostedAt: null,
    ownerId: 2,
    protectionEnabled: false,
    photos: [],
    privatePhotos: [],
  },
];
